In [1]:
import pandas as pd

In [2]:
A1 = pd.read_excel('weekly1419.xls').iloc[:, :17]

In [3]:
A2 =pd.read_excel('weekly_2021.xls')

In [4]:
A1 = A1.rename(columns = {'All  Cause': 'All Cause',
                    'Influenza and pneumonia (J10-J18)': 'Influenza and pneumonia (J09-J18)'})

In [5]:
AA = pd.concat([A1, A2]).fillna(0)

In [6]:
AA = AA.rename(columns = {'Jurisdiction of Occurrence': ' Jurisdiction', 
                          'MMWR Year': 'Year', 
                          'MMWR Week' : 'Week No',
       'Week Ending Date': 'Date',
    'Septicemia (A40-A41)': 'Septicemia',
       'Malignant neoplasms (C00-C97)': 'Malignant',
        'Diabetes mellitus (E10-E14)': 'Diabetes',
       'Alzheimer disease (G30)': 'Alzheimer', 
        'Influenza and pneumonia (J09-J18)': 'Influenza&Pneumonia',
       'Chronic lower respiratory diseases (J40-J47)': 'Chronic Resp',
       'Other diseases of respiratory system (J00-J06,J30-J39,J67,J70-J98)': 'Other Resp',
       'Nephritis, nephrotic syndrome and nephrosis (N00-N07,N17-N19,N25-N27)': 'Nephritis',
       'Symptoms, signs and abnormal clinical and laboratory findings, not elsewhere classified (R00-R99)': 'Abnormal',
       'Diseases of heart (I00-I09,I11,I13,I20-I51)': 'Heart',
       'Cerebrovascular diseases (I60-I69)': 'Cerebrovascular',
       'COVID-19 (U071, Multiple Cause of Death)': 'Multi C19',
       'COVID-19 (U071, Underlying Cause of Death)': 'C9 as Underlying'})

In [7]:
AA['Date'] = pd.to_datetime(AA['Date'])

In [ ]:
AA[AA['Jurisdiction of Occurrence'].str.contains('United States')].loc[:, 'All Cause':] = aaa

In [9]:
AA.to_csv('selected_diseases.csv')

In [ ]:
for i in AA.loc[:, 'All Cause':].columns:
    AA[AA['Jurisdiction of Occurrence'].str.contains('United States')].loc[:, i] = \
    AA[AA['Jurisdiction of Occurrence'].str.contains('United States')].loc[:, i].map(lambda x: x*1000 if x < 100 else x)

In [ ]:
usa = AA[AA['Jurisdiction of Occurrence'].str.contains('United States')]

In [10]:
AA

,Jurisdiction,Year,Week No,Date,All Cause,Natural Cause,Septicemia,Malignant,Diabetes,Alzheimer,Influenza&Pneumonia,Chronic Resp,Other Resp,Nephritis,Abnormal,Heart,Cerebrovascular,Multi C19,C9 as Underlying
0,United States,2014,1,2014-04-01,54.065,50.189,882.0,11.244,1.654,1.780,1.639,3.331,756.0,965.000,679.0,13.166,2.669,0.0,0.0
1,United States,2014,2,2014-11-01,56.353,52.450,905.0,11.504,1.735,1.917,1.910,3.444,845.0,1.098,665.0,13.663,2.738,0.0,0.0
2,United States,2014,3,2014-01-18,54.769,51.043,919.0,11.496,1.660,1.914,1.920,3.333,812.0,1.056,598.0,12.928,2.714,0.0,0.0
3,United States,2014,4,2014-01-25,54.223,50.560,845.0,11.629,1.602,1.862,1.765,3.467,753.0,1.029,622.0,12.813,2.720,0.0,0.0
4,United States,2014,5,2014-01-02,54.074,50.402,890.0,11.584,1.586,1.867,1.642,3.283,720.0,998.000,664.0,12.896,2.699,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3334,Wyoming,2021,6,2021-02-13,99.000,93.000,0.0,17.000,0.000,0.000,0.000,0.000,0.0,0.000,0.0,14.000,0.000,15.0,14.0
3335,Wyoming,2021,7,2021-02-20,104.000,96.000,0.0,17.000,0.000,0.000,0.000,0.000,0.0,0.000,0.0,17.000,0.000,0.0,0.0
3336,Wyoming,2021,8,2021-02-27,79.000,74.000,0.0,19.000,0.000,0.000,0.000,0.000,0.0,0.000,0.0,14.000,0.000,0.0,0.0
3337,Wyoming,2021,9,2021-03-06,60.000,58.000,0.0,13.000,0.000,0.000,0.000,0.000,0.0,0.000,0.0,11.000,0.000,0.0,0.0
3338,Wyoming,2021,10,2021-03-13,56.000,54.000,0.0,0.000,0.000,0.000,0.000,0.000,0.0,0.000,0.0,16.000,0.000,0.0,0.0